# Site settings
title: CK Landry Construction
email: 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Kevin Landry
email:
facebook_username:
twitter_username:
github_username:
address:
  - line: 
  - line: Ottawa
  # Feel free to add more lines here 
telephone: 613-323-1047
copyright:

# API settings
google_api_key: AIzaSyDwSOGyaCgpwodtDL1TUsP8ynAep3XDzRs

# Build settings
markdown: kramdown
